import '../styles/globals.css'
import Head from 'next/head'
import { CacheProvider } from '@emotion/react'
import createEmotionCache from '../styles/emotion-cache'
import { CustomAppProps } from './types'
import { RecoilRoot } from 'recoil'
import { StylesProvider } from '../styles/provider'
import { appWithTranslation } from 'next-i18next'
import * as React from 'react'

const clientSideEmotionCache = createEmotionCache()

function App({
  Component,
  emotionCache = clientSideEmotionCache,
  pageProps
}: CustomAppProps) {
  return (
    <CacheProvider value={emotionCache}>
      <Head>
        <title>Dev | Kamilo Vasquez</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <RecoilRoot>
        <StylesProvider>
          <Component {...pageProps} />
        </StylesProvider>
      </RecoilRoot>
    </CacheProvider>
  )
}

export default appWithTranslation(App)
